spring.application.name=${SPRING_APPLICATION_NAME:ecommerce}

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/EcommerceDatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0000}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

jwt.secret=${JWT_SECRET:D7ZaWSqCouKQfFrSZSixZpm0QHvRjRzBikvTdbQWhYk=}
jwt.expiration.ms=${JWT_EXPIRATION_MS:90000}

